Update PointSup/point_sup/detection_utils.py
It was updated for training with human keys, but the last update causes errors without other changed in files/codes as the changed codes gives 4 arguments without further updates on other codes.

TypeError: transform_instance_annotations() takes 3 positional arguments but 4 were given