Added the mapping from config to model checkpoint for the new baselines
Summary:
Related to https://github.com/facebookresearch/detectron2/issues/3225, but does **not** solve it.

# Overview of changes
FAIR recently published new [Mask R-CNN baselines](https://ai.facebook.com/blog/advancing-computer-vision-research-with-new-detectron2-mask-r-cnn-baselines/). The new config files have not yet been mapped to the corresponding model checkpoint files in the `model_zoo._ModelZooUrls` class. This was a relatively easy fix that simply follows the table given in the [MODEL_ZOO table](https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#new-baselines-using-large-scale-jitter-and-longer-training-schedule). If we run the following code snippet below:
```python
from detectron2 import model_zoo
model = model_zoo.get("new_baselines/mask_rcnn_regnetx_4gf_dds_FPN_400ep_LSJ.py", trained=True)
```

This used to give:
```
RuntimeError: new_baselines/mask_rcnn_regnetx_4gf_dds_FPN_400ep_LSJ not available in Model Zoo!
```

With these new changes, we get what we would expect and actually download and load the model:
```
model_final_f1362d.pkl: 173MB [01:13, 2.37MB/s]
The checkpoint state_dict contains keys that are not used by the model:
  proposal_generator.anchor_generator.cell_anchors.{0, 1, 2, 3, 4}
```

I am not entirely sure whether the warning is expected or something that requires fixing.

# Additional proposal
I personally am not a big fan of the naming. "new_baslines" seems too general to me and deviates from the already established naming conventions. This makes it less intuitive and not very robust to future updates. I would suggest moving the configs to `configs/COCO-InstanceSegmentation`. Similarly, I would then also move the checkpoint files accordingly to `https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/`. I did not implement these changes yet because I cannot change where the model files are stored and because I can imagine there to be an internal motivation not to change the naming anymore.

Pull Request resolved: https://github.com/facebookresearch/detectron2/pull/3228

Reviewed By: vaibhava0

Differential Revision: D29590936

Pulled By: ppwwyyxx

fbshipit-source-id: ffebeff845acfa2d9beb6d0e5472ff8670fbb457